Enforce minimum go version when runnign CMake if go is not disabled (#1580)
### Description of changes: 
The version specified in go.mod isn't enforced and users can hit weird
issues when building AWS-LC with old versions of go:
```
long build output
 util/embed_test_data.go:81:16: undefined: os.ReadFile
more build output
...
 make: *** [Makefile:117: all] Error 2
BUILD FAILED 
```

This is confusing because the go error can be easily overlooked.

### Call-outs:
This change isn't changing what version of Go builders need, just making
the requirement more clear.

### Testing:
Built locally and verified output `-- Go compiler 1.21.3 found` I also
tried raising the minimum version to 1.180 and verified it failed:
```
CMake Error at cmake/go.cmake:28 (message):
  Go compiler version must be at least 1.180.  Found version 1.21.3
Call Stack (most recent call first):
  CMakeLists.txt:26 (include)
```
And if you disable go the configure passes and checks nothing.


By submitting this pull request, I confirm that my contribution is made
under the terms of the Apache 2.0 license and the ISC license.