Validate or define ARM HWCAP2_XXX macros (#2164)
### Issues:
Addresses: aws/aws-lc-rs#681

### Description of changes: 
On some platforms ARM's `HWCAP2_XXX` macros might be defined in system
header files, causing compilation failure due to their being redefined
here.
```
.../aws-lc/crypto/fipsmodule/cpucap/cpu_arm_linux.h:35:9: error: 'HWCAP2_AES' redefined [-Werror]
     35 | #define HWCAP2_AES (1 << 0)
        |         ^~~~~~~~~~
  In file included from .../armv7ve-libreelec-linux-gnueabihf/sysroot/usr/include/bits/hwcap.h:53:9: note: this is the location of the previous definition
     53 | #define HWCAP2_AES              1
        |         ^~~~~~~~~~
```


By submitting this pull request, I confirm that my contribution is made
under the terms of the Apache 2.0 license and the ISC license.