cpu_ppc64le.c: fix build on FreeBSD
FreeBSD uses elf_aux_info() function instead of getauxval():
  In file included from /wrkdirs/usr/ports/security/rustls-ffi/work/rustls-ffi-0.15.0/cargo-crates/aws-lc-sys-0.24.0/aws-lc/crypto/fipsmodule/bcm.c:86:
  /wrkdirs/usr/ports/security/rustls-ffi/work/rustls-ffi-0.15.0/cargo-crates/aws-lc-sys-0.24.0/aws-lc/crypto/fipsmodule/cpucap/cpu_ppc64le.c:72:28: error: call to undeclared function 'getauxval'; ISO C99 and later do not support implicit function declarations [-Werror,-Wimplicit-function-declaration]
     72 |   OPENSSL_ppc64le_hwcap2 = getauxval(AT_HWCAP2);
        |                            ^