Fix test to conform with observed behavior in CI
```
[----------] 1 test from BIOTest
[ RUN      ] BIOTest.TextFile
..\crypto\bio\bio_test.cc(200): error: Expected equality of these values:
  "test\n"
  std::string(contents)
    Which is: "test\r\r\n"
[  FAILED  ] BIOTest.TextFile (1 ms)
[----------] 1 test from BIOTest (1 ms total)
```