Remove sys headers from bio.h (#2508)
Some internal builds are failing due to the duplicate header file
references that `bio.h` has.
```
/usr/include/bits/types/struct_iovec.h:26:8: error: redefinition of 'struct iovec'
struct iovec
        ^~~~~
In file included from src/core/tsi/alts/crypt/aes_gcm.cc:23:0:
./src/core/tsi/alts/crypt/gsec.h:30:8: note: previous definition of 'struct iovec'
struct iovec {
```

The `sockaddr` references requires the `<sys/socket.h>` header to exist,
but it turns out we never actually implemented
`BIO_dgram_get_mtu_overhead`. Removing `BIO_dgram_get_mtu_overhead` for
now allows us to get around the "redefinition failure".

OpenSSL gets around the `sockaddr` by containing
`BIO_dgram_get_mtu_overhead` in a macro pointing to
`BIO_ctrl`. We'll likely have to do the same here when we eventually implement
`BIO_dgram_get_mtu_overhead`.

### Callouts
I'll introduce CI for the issue in another PR.

By submitting this pull request, I confirm that my contribution is made
under the terms of the Apache 2.0 license and the ISC license.