Aarch64 SHA-512 crash fix (#371)
Fix the crash caused by setting the SHA-512 capability bit in `OPENSSL_armcap` when it's not available.

The actual AArch64 capabilities, retrieved by `getauxval()`, if available, are compared against those requested in the environment variable OPENSSL_armcap when set.
This is in order to avoid crashing in the middle of an application which calls SHA-512 functions. Now the application wouldn't start and a "Fatal Error" is sent to the output, for example:
```
$ export OPENSSL_armcap=0x7D && ./crypto/crypto_test
Fatal Error: HW capability found: 0x3D, but HW capability requested: 0x7D.
```