tool-openssl: Fix warning 'strnlen' specified bound 4096 exceeds source size 128 (#2556)
Caught when working on writing an RPM specfile and the
`-Werror=stringop-overread` was used.

```
In function 'createTempDirPath',
    inlined from 'SetUp' at /home/mcgrails/rpmbuild/BUILD/aws-lc-1.55.0/tool-openssl/rehash_test.cc:22:5:
/home/mcgrails/rpmbuild/BUILD/aws-lc-1.55.0/crypto/test/test_util.cc:228:17: error: 'strnlen' specified bound 4096 exceeds source size 128 [-Werror=stringop-overread]
  228 |   return strnlen(buffer, PATH_MAX);
      |                 ^
/home/mcgrails/rpmbuild/BUILD/aws-lc-1.55.0/crypto/test/test_util.cc: In member function 'SetUp':
/home/mcgrails/rpmbuild/BUILD/aws-lc-1.55.0/tool-openssl/rehash_test.cc:82:8: note: source object declared here
   82 |   char test_dir[128];
      |        ^
lto1: all warnings being treated as errors
make[3]: *** [/tmp/cckPSIxl.mk:2: /tmp/cc37pBln.ltrans0.ltrans.o] Error 1
make[3]: *** Waiting for unfinished jobs....
lto-wrapper: fatal error: make returned 2 exit status
```

By submitting this pull request, I confirm that my contribution is made
under the terms of the Apache 2.0 license and the ISC license.