Modified posix builds to enable dilithium by default (#2034)
### Issues:
Addresses #P175809809

### Description of changes: 
As we prepare ML-DSA and the removal of the `enable_dilithium` flag, we
prepare our builds to all enable dilithium. This should also catch
addition bugs in the CI.

One such bug has already been found by testing this addition, that has
also been addressed in this PR:

```
In file included from /crypto/dilithium/ml_dsa.c:20:
/crypto/dilithium/./pqcrystals_dilithium_ref_common/sign.c: In function ‘crypto_sign_keypair_internal’:
/crypto/dilithium/./pqcrystals_dilithium_ref_common/sign.c:54:9: error: ‘s1’ may be used uninitialized [-Werror=maybe-uninitialized]
 54 | s1hat = s1;
 | ~~~~^~
crypto/dilithium/./pqcrystals_dilithium_ref_common/sign.c:35:12: note: ‘s1’ declared here
 35 | polyvecl s1, s1hat;
 | ^~
```

### Testing:
Found through testing for linux builds/

By submitting this pull request, I confirm that my contribution is made
under the terms of the Apache 2.0 license and the ISC license.

---------

Co-authored-by: Andrew Hopkins <andhop@amazon.com>