Add support for s390x architecture. (#1431)
### Description of changes: 

Add support for s390x architecture.

This is pretty trivial change (a few defines), since the big-endian
support was previously added for PowerPC architectures.


### Call-outs:

There is a false-positive error when compiling using
`s390x-linux-gnu-gcc-11` with `-O3` (i.e. `Release` profile):
```
crypto/pem/pem_lib.c:705:11: error: ‘strncmp’ of strings of length 1 and 9 and bound of 9 evaluates to nonzero [-Werror=string-compare]
 705 |       if (strncmp(buf, "-----END ", 9) == 0) {
     |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```
but there are no issues when using `-O2` or when building with
`s390x-linux-gnu-gcc-12`.


### Testing:

All tests from `run_cross_tests.sh`, i.e.
```
crypto/crypto_test --gtest_also_run_disabled_tests
crypto/urandom_test
crypto/mem_test
crypto/mem_set_test
crypto/dynamic_loading_test

ssl/ssl_test
ssl/integration_test
```
passed, with the exception of `BIOTest.InvokeConnectCallback`, which
fails for me on all platforms.


By submitting this pull request, I confirm that my contribution is made
under the terms of the Apache 2.0 license and the ISC license.


cc @andrewhop @justsmth

---------

Signed-off-by: Piotr Sikora <piotr@aviatrix.com>
Co-authored-by: Justin Smith <justsmth@amazon.com>
Co-authored-by: Justin W Smith <103147162+justsmth@users.noreply.github.com>