crypto: remove kBoringSSLBinaryTag
This was never updated and not in use.  Remove this to simplify the code
and avoid an issue on ARM64 Windows.

~~~
D:\a\firebase-cpp-sdk\firebase-cpp-sdk\BinaryCache\firebase\external\src\boringssl\crypto\mem.c(152): error C2220: the following warning is treated as an error
D:\a\firebase-cpp-sdk\firebase-cpp-sdk\BinaryCache\firebase\external\src\boringssl\crypto\mem.c(152): warning C4746: volatile access of 'kBoringSSLBinaryTag' is subject to /volatile:<iso|ms> setting; consider using __iso_volatile_load/store intrinsic functions
~~~

Change-Id: Iedb0999e38c769add5bb1d5623e038b17f8f245f
Reviewed-on: https://boringssl-review.googlesource.com/c/boringssl/+/63325
Reviewed-by: David Benjamin <davidben@google.com>
Reviewed-by: Adam Langley <agl@google.com>
Commit-Queue: Adam Langley <agl@google.com>
(cherry picked from commit 5d58c559ace6a24ea6613e412b26bd4c50668ab3)